# Generated by Django 3.0.4 on 2020-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ManyToManyField(null=True, to='stock.Provider'),
        ),
    ]
